### ISSUE TITLE
intitle option issue

### ISSUE THREAD

**Issue by nicolas1308** [josephwright/biblatex-nature#11]
Hello,
I'm trying to use the intitle=true option for inbook and incollection. 
I systematically have and error with overleaf ": `intitle' undefined in families 
Could you help solving this issue ? 

Best regards. 
Nicolas

**Comment by josephwright** [comment]
Please add an example of your input: this should all work fine.

**Comment by nicolas1308** [comment]
Hello,
I used the following : 

\usepackage[style=nature,backend=biber,safeinputenc,doi=false,isbn=false,url=false,date=year,intitle=true]{biblatex}

With this kind of reference in the .bib file : 

@incollection{Snyder2017MilestonesChromatography,
    title = {{Milestones in the development of liquid chromatography}},
    year = {2017},
    booktitle = {Liquid Chromatography: Fundamentals and Instrumentation},
    author = {Snyder, Lloyd R. and Dolan, John W.},
    edition = {2nd ed.},
    publisher = {Elsevier}
}

When the option intitle remove, the compilation does right but the « title » field is not showed for @incollection and @book.
With intitle=true, the complication stops with the following error : Package xkeyval Error: `intitle' undefined in families `blx@opt@pre'.

Thanks for your help. 

Regards

**Comment by josephwright** [comment]
This all works in the current release: I can only imagine you have an old version. Can you check the version data in your `.log` file?

**Comment by nicolas1308** [comment]
It seems you were right : the 1.2g version is loaded in the log file/ 

Package biblatex Info: Trying to load bibliography style 'nature'...
Package biblatex Info: ... file 'nature.bbx' found.
(/usr/share/texlive/texmf-dist/tex/latex/biblatex-nature/nature.bbx
File: nature.bbx 2016/03/13 v1.2g biblatex bibliography style

This is strange because the overleaf plateforme is updated regularly. 
Any idea how I can patch this ?

**Comment by josephwright** [comment]
On 22/06/2019 11:44, nicolas1308 wrote:
> It seems you were right : the 1.2g version is loaded in the log file/
> 
> Package biblatex Info: Trying to load bibliography style 'nature'...
> Package biblatex Info: ... file 'nature.bbx' found.
> (/usr/share/texlive/texmf-dist/tex/latex/biblatex-nature/nature.bbx
> File: nature.bbx 2016/03/13 v1.2g biblatex bibliography style
> 
> This is strange because the overleaf plateforme is updated regularly.
> Any idea how I can patch this ?
> 
> 

Add a copy of nature.bbx from CTAN to your project: that should then be 
used in preference to the system one.

Joseph

**Comment by nicolas1308** [comment]
Worked perfectly ! 
Problem solved. Thanes for your time ! 
Nicolas
