### ISSUE TITLE
reference numbers should be superscript, not in brackets

### ISSUE THREAD

**Issue by rmolina** [josephwright/biblatex-nature#12]
From [Nature's Formatting guide](https://www.nature.com/nature/for-authors/formatting-guide):

> When cited in the text, reference numbers are superscript, not in brackets unless they are likely to be confused with a superscript number.

However, `\parencite{}` and `\textcite{}` both use numbers in brackets. Is there a way to change this?

**Comment by josephwright** [comment]
Both of these are meant for 'textual' citations, and in particular `\parencite` is more useful for author-year styles. Notably, these commands are supposed to provide predictable output.Normally I would say one mainly uses `\autocite`, which can be `\supercite` or `\textcite` or ... depending on the context.
