### ISSUE TITLE
citenum

### ISSUE THREAD

**Issue by CommonClimate** [josephwright/biblatex-nature#4]
Hi,
I should preface this by stating that I am a longtime bibtex user and only recently started using biblatex. I work on Mac OS 10.10.5 using TexShop 3.59 with the pdflatexmk engine.

I was very happy to find your nature biblatex style, since I am preparing an article for an NPG journal. Using \autocite results in nicely formatted superscript citations, but I am wondering how to generate a numeric (non-superscript) citation: e.g. "reference [15] argues that ...". 
Using natbib I could do so via the \citenum command, and can't figure out a good way to do it with this package.  Thanks in advance for your help.
CC

**Comment by e-kwsm** [comment]
It is work of BibLaTeX but not this package.
To generate something like "reference [15] argues that ...", use `\cite` or `\parencite`.
See the document of BibLaTeX for detai.

**Comment by e-kwsm** [comment]
To use `\autocite` as you want, pass option `autocite=plain` or `inline` to biblatex (they behave like `\cite` and `\parencite`, respectivey).

**Comment by CommonClimate** [comment]
thanks @e-kwsm. What I want is to use `\autocite` as a superscript  in the majority of cases, so configuring it to behave like `\cite` or `\parencite` isn't going to work. 
There are just a handful of instances in the document where I need a `\citenum` command, so I defined it as follows:
```
\DeclareCiteCommand{\citenum}
  {}
  {\printfield{labelnumber}}
  {}
  {}
```
I was just wondering if there was a more elegant solution.

**Comment by josephwright** [comment]
As noted, you should use `\autocite` or `\supercite` for 'general' citations and `\cite` for 'non-formatted' callouts. This is part of the standard `biblatex` interface and not specific to the `nature` style.

**Comment by CommonClimate** [comment]
My mistake, then. As I said, I am still very new to biblatex. Sorry for the confusion!
