### ISSUE TITLE
Removing brackets around URLs

### ISSUE THREAD

**Issue by CommonClimate** [josephwright/biblatex-nature#7]
when I use the `@online` reference type, the URLs are enclosed in angle brackets <>. Yet Nature publication group guidelines on references (e.g. http://www.nature.com/sdata/publish/submission-guidelines#references) ask for no such brackets. Is there an easy way to remove those from the biblatex call, or does it require fumbling with the bbx file. If so, how?  
Thanks in advance,
El Niño

**Comment by josephwright** [comment]
You want
```latex
\DeclareFieldFormat{url}{\url{#1}}
```
I think _Nature_ used to use angle brackets here, but they seem to have dropped them: I'll update the style.

**Comment by CommonClimate** [comment]
Fantastic, that command does the trick, and glad the issue helped in a small way to make the package compliant with the latest _Nature_ guidelines
