### ISSUE TITLE
comma following issue number is in bold?

### ISSUE THREAD

**Issue by hongenxu** [josephwright/biblatex-nature#8]
Hi, 

I used biblatex-nature version 1.3b with the following command in latex, 
`\usepackage[backend=bibtex,style=nature]{biblatex}`

the resulting reference is as follows 
Stratton, M. R. Exploring the genomes of cancer cells: progress and promise. Science
**331,** 1553–1558 (2011). 

both issue number and comma are in bold? Is comma in bold expected ?

Best,
Hongen

**Comment by josephwright** [comment]
I'll check they still do, but certainly up to recently _Nature_ use traditional typography here, where the formatting of text also applies to following punctuation.

**Comment by josephwright** [comment]
I've now checked this in  the latest print edition: they retain the traditional approach here (so the behaviour is as-expected).
