### ISSUE TITLE
Citation numbers appear in square bracket instead of as numeric superscripts

### ISSUE THREAD

**Issue by cryptic0** [josephwright/biblatex-nature#9]
When using this citation style, I am getting numerical references but they are of this fashion:

``Fisher [1]`` instead of ``Fisher``<sup>1</sup>

My preamble

``
\usepackage[backend=biber,style=nature,articletitle=true,intitle=true,natbib=true]{biblatex}
``
Citation command
``
This is a citation \citep{Fisher1930}.
``

**Comment by josephwright** [comment]
You are using the wrong citation command: you want `\supercite` or `\autocite`. See the core `biblatex` docs on this.
